language: java
jdk:
 - oraclejdk8
sudo: false

addons:
  sonarcloud:
    organization: "crejczyk-github"
    token:
      secure: "44049eba83d0b9b33ca261c675fb55175c2e0d90"

      
before_script: "cd social-multiplication"

#script: "mvn clean verify"
script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
