version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.6-management
    hostname: "rabbit1"
    ports:
      - "15672:15672"  # management port (guest:guest)
      - "5672:5672"    # amqp port
    labels:
      NAME: "rabbitmq_docker"
       
  service-registry:
    image: service-registry
    ports:
     - "8761:8761"
  
  gateway:
    image: gateway
    links:
     - service-registry
    ports:
     - "8000:8000"
        
  social-multiplication:
    image: social-multiplication
    links:
     - rabbitmq
     - service-registry
   # deploy:
   #   mode: replicated
   #   replicas: 2
      
  gamification:
    image: gamification
    links:
     - rabbitmq
     - service-registry